# Generated by Django 2.2.3 on 2019-08-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=49)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('ifsc_code', models.CharField(db_index=True, max_length=11, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=74)),
                ('address', models.CharField(max_length=195)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=26)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banks.Bank')),
            ],
        ),
    ]
